# Generated by Django 5.0.1 on 2024-01-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
