# Generated by Django 5.0.1 on 2024-01-21 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hangar', '0004_alter_feature_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='latest',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
